buses/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('busstops.urls')),
]

handler404 = 'busstops.views.not_found'

busstops/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.urls import path
from django.contrib import staticfiles
from django.contrib.sitemaps.views import sitemap
from haystack.views import SearchView
from .forms import CustomSearchForm
from . import views

urlpatterns = [
    path('', views.index),
    path('offline', views.offline),
    path('contact', views.contact),
    path('awin-transaction', views.awin_transaction),
    path('cookies', views.cookies),
    path('data', views.data),
    path('apps', views.apps),
    path('map', views.hugemap),
    path('stops.json', views.stops),
    path('regions/<pk>', views.RegionDetailView.as_view(), name='region_detail'),
    path('places/<int:pk>', views.PlaceDetailView.as_view(), name='place_detail'),
    url(r'^(admin-)?areas/(?P<pk>\d+)', views.AdminAreaDetailView.as_view(), name='adminarea_detail'),
    path('districts/<int:pk>', views.DistrictDetailView.as_view(), name='district_detail'),
    url(r'^localities/(?P<pk>[ENen][Ss]?[0-9]+)', views.LocalityDetailView.as_view()),
    path('localities/<slug>', views.LocalityDetailView.as_view(), name='locality_detail'),
    path('stops/<pk>.json', views.stop_json),
    path('stops/<pk>', views.StopPointDetailView.as_view(), name='stoppoint_detail'),
    url(r'^operators/(?P<pk>[A-Z]+)$', views.OperatorDetailView.as_view()),
    path('operators/<slug>', views.OperatorDetailView.as_view(), name='operator_detail'),
    path('operators/<slug>/vehicles', views.operator_vehicles),
    path('services/<slug>/vehicles', views.service_vehicles_history),
    path('services/<pk>.xml', views.service_xml),
    path('services/<slug>', views.ServiceDetailView.as_view(), name='service_detail'),
    path('licences/<licence_number>', views.RegistrationView.as_view(), name='registration_list'),
    path('registrations/<path:registration__registration_number>', views.VariationView.as_view(),
         name='variation_list'),
    path('vehicles', views.vehicles),
    path('vehicles.json', views.vehicles_json),
    path('vehicles/<int:pk>', views.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('sitemap.xml', sitemap, {
        'sitemaps': {
             'operators': views.OperatorSitemap,
             'services': views.ServiceSitemap,
        }
    }),
    path('search', SearchView(form_class=CustomSearchForm)),
    path('journey', views.journey),
]


if settings.DEBUG and hasattr(staticfiles, 'views'):
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + (
        static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static.static('/', document_root=settings.STATIC_ROOT)
    )

busstops/models.py
"Model definitions"

import re
import os
import zipfile
import time
from urllib.parse import urlencode
from datetime import date
from autoslug import AutoSlugField
from django.conf import settings
from django.contrib.gis.db import models
from django.contrib.postgres.fields import JSONField
from django.core.cache import cache
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.functional import cached_property
from django.utils.text import slugify
from multigtfs.models import Route
from timetables import txc, northern_ireland, gtfs
from .utils import sign_url


TIMING_STATUS_CHOICES = (
    ('PPT', 'Principal point'),
    ('TIP', 'Time info point'),
    ('PTP', 'Principal and time info point'),
    ('OTH', 'Other bus stop'),
)
SERVICE_ORDER_REGEX = re.compile(r'(\D*)(\d*)(\D*)')


class ValidateOnSaveMixin(object):
    """https://www.xormedia.com/django-model-validation-on-save/"""
    def save(self, force_insert=False, force_update=False, **kwargs):
        if not (force_insert or force_update):
            self.full_clean()
        super().save(force_insert, force_update, **kwargs)


@python_2_unicode_compatible
class Region(models.Model):
    """The largest type of geographical area"""
    id = models.CharField(max_length=2, primary_key=True)
    name = models.CharField(max_length=48)

    class Meta():
        ordering = ('name',)

    def __str__(self):
        return self.name

    def the(self):
        """Return the name for use in a sentence,
        with the definite article prepended if appropriate"""
        if self.name[-2:] in ('ds', 'st'):
            return 'the ' + self.name
        else:
            return self.name

    def get_absolute_url(self):
        return reverse('region_detail', args=(self.id,))


@python_2_unicode_compatible
class AdminArea(models.Model):
    """An administrative area within a region,
    or possibly a national transport (rail/air/ferry) network
    """
    id = models.PositiveIntegerField(primary_key=True)
    atco_code = models.PositiveIntegerField()
    name = models.CharField(max_length=48)
    short_name = models.CharField(max_length=48, blank=True)
    country = models.CharField(max_length=3, blank=True)
    region = models.ForeignKey(Region, models.CASCADE)

    class Meta():
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('adminarea_detail', args=(self.id,))


@python_2_unicode_compatible
class District(models.Model):
    """A district within an administrative area.
    Note: some administrative areas *do not* have districts.
    """
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=48)
    admin_area = models.ForeignKey(AdminArea, models.CASCADE)

    class Meta():
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('district_detail', args=(self.id,))


@python_2_unicode_compatible
class Locality(models.Model):
    """A locality within an administrative area,
    and possibly within a district.

    Localities may be children of other localities...
    """
    id = models.CharField(max_length=48, primary_key=True)
    name = models.CharField(max_length=48)
    slug = AutoSlugField(always_update=True, populate_from='get_qualified_name', editable=True, unique=True)
    # short_name?
    qualifier_name = models.CharField(max_length=48, blank=True)
    admin_area = models.ForeignKey(AdminArea, models.CASCADE)
    district = models.ForeignKey(District, models.SET_NULL, null=True, blank=True)
    parent = models.ForeignKey('Locality', models.SET_NULL, null=True, editable=False)
    latlong = models.PointField(null=True, blank=True)
    adjacent = models.ManyToManyField('Locality', related_name='neighbour', blank=True)

    class Meta():
        ordering = ('name',)

    def __str__(self):
        return self.name or self.id

    def get_qualified_name(self):
        """Return the name and qualifier (e.g. 'Reepham, Lincs')"""
        if self.qualifier_name:
            return "%s, %s" % (self.name, self.qualifier_name)
        return str(self)

    def get_absolute_url(self):
        return reverse('locality_detail', args=(self.slug,))


@python_2_unicode_compatible
class StopArea(models.Model):
    """A small area containing multiple stops, such as a bus station"""

    id = models.CharField(max_length=16, primary_key=True)
    name = models.CharField(max_length=48)
    admin_area = models.ForeignKey(AdminArea, models.CASCADE)

    TYPE_CHOICES = (
        ('GPBS', 'on-street pair'),
        ('GCLS', 'on-street cluster'),
        ('GAIR', 'airport building'),
        ('GBCS', 'bus/coach station'),
        ('GFTD', 'ferry terminal/dock'),
        ('GTMU', 'tram/metro station'),
        ('GRLS', 'rail station'),
        ('GCCH', 'coach service coverage'),
    )
    stop_area_type = models.CharField(max_length=4, choices=TYPE_CHOICES)

    parent = models.ForeignKey('StopArea', models.SET_NULL, null=True, editable=False)
    latlong = models.PointField(null=True)
    active = models.BooleanField()

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class DataSource(models.Model):
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField(blank=True)
    datetime = models.DateTimeField()

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Place(models.Model):
    source = models.ForeignKey(DataSource, models.CASCADE)
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    latlong = models.PointField(null=True, blank=True)
    polygon = models.PolygonField(null=True, blank=True)
    parent = models.ForeignKey('Place', models.SET_NULL, null=True, editable=False)

    class Meta():
        unique_together = ('source', 'code')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('place_detail', args=(self.pk,))


@python_2_unicode_compatible
class StopPoint(models.Model):
    """The smallest type of geographical point.
    A point at which vehicles stop"""
    atco_code = models.CharField(max_length=16, primary_key=True)
    naptan_code = models.CharField(max_length=16, db_index=True, blank=True)

    common_name = models.CharField(max_length=48)
    landmark = models.CharField(max_length=48, blank=True)
    street = models.CharField(max_length=48, blank=True)
    crossing = models.CharField(max_length=48, blank=True)
    indicator = models.CharField(max_length=48, blank=True)

    latlong = models.PointField(null=True)

    stop_area = models.ForeignKey(StopArea, models.SET_NULL, null=True, editable=False)
    locality = models.ForeignKey('Locality', models.SET_NULL, null=True, editable=False)
    suburb = models.CharField(max_length=48, blank=True)
    town = models.CharField(max_length=48, blank=True)
    locality_centre = models.BooleanField()

    places = models.ManyToManyField(Place, blank=True)

    heading = models.PositiveIntegerField(null=True, blank=True)

    BEARING_CHOICES = (
        ('N', 'north'),
        ('NE', 'north-east'),
        ('E', 'east'),
        ('SE', 'south-east'),
        ('S', 'south'),
        ('SW', 'south-west'),
        ('W', 'west'),
        ('NW', 'north-west')
    )
    bearing = models.CharField(max_length=2, choices=BEARING_CHOICES, blank=True)

    STOP_TYPE_CHOICES = (
        ('AIR', 'Airport entrance'),
        ('GAT', 'Air airside area'),
        ('FTD', 'Ferry terminal/dock entrance'),
        ('FER', 'Ferry/dock berth area'),
        ('FBT', 'Ferry berth'),  # ?
        ('RSE', 'Rail station entrance'),
        ('RLY', 'Rail platform access area'),
        ('RPL', 'Rail platform'),  # ?
        ('TMU', 'Tram/metro/underground entrance'),
        ('MET', 'MET'),  # ?
        ('PLT', 'Metro and underground platform access area'),
        ('BCE', 'Bus/coach station entrance'),
        ('BCS', 'Bus/coach bay/stand/stance within bus/coach station'),
        ('BCQ', 'Bus/coach bay'),  # ?
        ('BCT', 'On street bus/coach/tram stop'),
        ('TXR', 'Taxi rank (head of)'),
        ('STR', 'Shared taxi rank (head of)'),
    )
    stop_type = models.CharField(max_length=3, choices=STOP_TYPE_CHOICES, blank=True)

    BUS_STOP_TYPE_CHOICES = (
        ('MKD', 'Marked (pole, shelter etc)'),
        ('HAR', 'Hail and ride'),
        ('CUS', 'Custom (unmarked, or only marked on road)'),
        ('FLX', 'Flexible zone'),
    )
    bus_stop_type = models.CharField(max_length=3, choices=BUS_STOP_TYPE_CHOICES, blank=True)

    timing_status = models.CharField(max_length=3, choices=TIMING_STATUS_CHOICES, blank=True)

    admin_area = models.ForeignKey('AdminArea', models.SET_NULL, null=True, blank=True)
    active = models.BooleanField(db_index=True)

    osm = JSONField(null=True, blank=True)

    class Meta():
        ordering = ('common_name', 'atco_code')

    def __str__(self):
        if self.indicator:
            return '%s (%s)' % (self.common_name, self.indicator)
        return self.common_name

    def get_heading(self):
        """Return the stop's bearing converted to degrees, for use with Google Street View."""
        if self.heading:
            return self.heading
        headings = {
            'N': 0,
            'NE': 45,
            'E': 90,
            'SE': 135,
            'S': 180,
            'SW': 225,
            'W': 270,
            'NW': 315,
        }
        return headings.get(self.bearing)

    prepositions = {'opp', 'adj', 'at', 'o/s', 'nr', 'before', 'after', 'by', 'on', 'in', 'opposite', 'outside'}

    def indicator_in_prepositions(self):
        return self.indicator in self.prepositions

    def get_qualified_name(self):
        if self.locality:
            locality_name = self.locality.name.replace(' Town Centre', '').replace(' City Centre', '')

busstops/forms.py
import requests
from django import forms
from django.db.models import Q
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import Point, Polygon
from django.core.exceptions import ValidationError
from haystack.forms import SearchForm
from haystack.query import SQ, AutoQuery
from ukpostcodeutils import validation
from antispam.honeypot.forms import HoneypotField
from antispam import akismet
from .models import Locality


session = requests.Session()


class ContactForm(forms.Form):
    name = forms.CharField(label='Name')
    email = forms.EmailField(label='Email address')
    message = forms.CharField(label='Message', widget=forms.Textarea)
    spam_honeypot_field = HoneypotField()
    referrer = forms.CharField(label='Referrer', required=False,
                               widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        if self.request and self.is_valid() and akismet.check(
            request=akismet.Request.from_django_request(self.request),
            comment=akismet.Comment(
                content=self.cleaned_data['message'],
                type='comment',
                author=akismet.Author(
                    name=self.cleaned_data['name'],
                    email=self.cleaned_data['email']
                )
            )
        ):
            raise ValidationError('Spam detected', code='spam-protection')


class CustomSearchForm(SearchForm):
    """https://django-haystack.readthedocs.io/en/master/boost.html#field-boost"""
    def get_postcode(self):
        q = self.cleaned_data['q']
        q = ''.join(q.split()).upper()
        if validation.is_valid_postcode(q):
            res = session.get('https://api.postcodes.io/postcodes/' + q, timeout=2)
            if not res.ok:
                return ''
            result = res.json()['result']
            point = Point(result['longitude'], result['latitude'], srid=4326)
            bbox = Polygon.from_bbox((point.x - .05, point.y - .05, point.x + .05, point.y + .05))
            return Locality.objects.filter(
                latlong__within=bbox
            ).filter(
                Q(stoppoint__active=True) | Q(locality__stoppoint__active=True)
            ).distinct().annotate(
                distance=Distance('latlong', point)
            ).order_by('distance').defer('latlong')[:2]

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        q = self.cleaned_data['q']
        sqs = self.searchqueryset.filter(SQ(name=AutoQuery(q)) | SQ(text=AutoQuery(q)))

        if self.load_all:
            sqs = sqs.load_all()

        return sqs.highlight()

busstops/templates/busstops/adminarea_detail.html
{% extends 'page.html' %}

{% block content %}

<h1>{{ adminarea }}</h1>

{% if districts %}
    <h2>Districts in {{ adminarea }}</h2>

    {% include 'list.html' with list=districts %}
{% endif %}


{% if localities %}
    <h2>Places in {{ adminarea }}</h2>

    {% include 'list.html' with list=localities %}
{% endif %}

{% if services %}
    <h2>{% include 'modes.html' with modes=modes noun='services' %} in {{ adminarea }}</h2>

    {% include 'services.html' with services=services %}
{% endif %}

{% endblock %}

busstops/templates/busstops/district_detail.html
{% extends 'page.html' %}

{% block content %}

<h1>{{ district }}</h1>

<h2>Places in {{ district }}</h2>

{% include 'list.html' with list=localities %}

{% endblock %}

busstops/templates/busstops/locality_detail.html
{% extends 'page.html' %}

{% block content %}

<h1>{{ locality.get_qualified_name }}</h1>

{% if localities %}
    <h2>Places in {{ locality }}</h2>

    {% include 'list.html' with list=localities %}
{% endif %}

{% if stops %}
    <h2>Stops in {{ locality }}</h2>

    <div class="map-wrapper"><div id="map"></div></div>

    {% include 'stops.html' with stops=stops %}
{% endif %}

{% if services %}
    <h2>{% include 'modes.html' with modes=modes noun='services' %}</h2>

    <ul>
        {% for service in services %}
            <li>
                <a href="{{ service.get_absolute_url }}">{{ service }}</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% if adjacent %}
    <h2>Near {{ locality }}</h2>

    <ul>
        {% for locality in adjacent %}
            <li>
                <a href="{{ locality.get_absolute_url }}">{{ locality }}</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

busstops/templates/busstops/operator_detail.html
{% extends amp|yesno:'page_amp.html,page.html' %}

{% load urlise %}

{% block head %}
    <link rel="amphtml" href="https://bustimes.org{{ object.get_absolute_url }}?amp" />
    <link rel="shortlink" href="https://bustimes.org/operators/{{ object.id }}" />
{% endblock %}

{% block content %}

<div itemscope itemtype="http://schema.org/LocalBusiness">

<h1 itemprop="name">{{ object }}</h1>

<p>{{ object.get_a_mode }} operating company in <a href="{{ object.region.get_absolute_url }}">{{ object.region.the }}</a></p>

{% if operator.get_licences %}
    <p>PSV license number: {% for licence in operator.get_licences %}<a href="{{ licence.get_absolute_url }}">{{ licence }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
{% endif %}

{% if operator.vehicle_set.exists %}
    <p>For anoraks: <a href="{{ object.get_absolute_url }}/vehicles">an incomplete {{ object }} fleet list</a></p>
{% endif %}

{% for note in notes %}
    <p class="warning">{{ note|safe }}</p>
{% endfor %}

<h2>{% include 'modes.html' with modes=modes noun='services' %} operated by {{ object }}</h2>

{% include 'services.html' with services=services %}

{% if object.address or object.url or object.email or object.phone %}
    <h2>Contact {{ object }}</h2>

    <div class="contact-details">
    {% if object.address %}
        <p itemprop="address">{{ object.address|linebreaksbr }}</p>
    {% endif %}
    {% if object.url %}
        <p itemprop="url">{{ object.url|urlise }}</p>
    {% endif %}
    {% if object.email %}
        {% load email_obfuscator %}
        <p itemprop="email">{{ object.email|obfuscate_mailto }}</p>
    {% endif %}
    {% if object.phone %}
        <p itemprop="telephone">{{ object.phone }}</p>
    {% endif %}
    {% if object.twitter %}
        {% for handle in object.twitter.split %}
            <p><a href="https://twitter.com/{{ handle }}">@{{ handle }} on Twitter</a></p>
        {% endfor %}
    {% endif %}
    </div>
{% endif %}

</div>

{% endblock %}

busstops/templates/busstops/place_detail.html
{% extends 'page.html' %}

{% block content %}

<h1>{{ object }}</h1>

{% if places %}
    <h2>Places in {{ object }}</h2>

    {% include 'list.html' with list=places %}
{% endif %}

{% if stops %}
    <h2>Stops in {{ object }}</h2>

    {% include 'list.html' with list=stops %}
{% endif %}

{% endblock %}

busstops/templates/busstops/region_detail.html
{% extends 'page.html' %}

{% block content %}

<h1>{{ region }}</h1>

{% if areas %}
    <h2>Areas in {{ region.the }}</h2>

    {% include 'list.html' with list=areas %}
{% elif districts %}
    <h2>Districts in {{ region.the }}</h2>

    {% include 'list.html' with list=districts %}
{% endif %}

{% if services %}
    <h2>Bus services in {{ region.the }}</h2>

    {% include 'services.html' with services=services %}
{% endif %}

{% if operators %}
    <h2>Transport operating companies in {{ region.the }}</h2>

    {% include 'list.html' with list=operators %}
{% endif %}

{% endblock %}

busstops/templates/busstops/registration_list.html
{% extends 'page.html' %}

{% block title %}{{ operator }} – {{ operator.operator }} – Bus Times{% endblock %}

{% block content %}

<h1>{{ operator }}</h1>

{% if object_list %}
    <h2>Current and future bus service registrations</h2>

    <table>
        <tr>
            <th colspan="2"></th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col">Via</th>
            <th scope="col">Last changed</th>
        </tr>
        {% for registration in object_list %}
            <tr>
                <td><a href="{{ registration.get_absolute_url }}">{{ registration.registration_number }}</a></td>
                <td>{{ registration.service_number }}</td>
                <td>{{ registration.start_point }}</td>
                <td>{{ registration.finish_point }}</td>
                <td>{{ registration.via }}</td>
                <td>{{ registration.date|date:"j M y" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

<h2>Cancelled bus service registrations</h2>

{% if cancelled %}
    <table>
        <tr>
            <th colspan="2"></th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col">Via</th>
            <th scope="col">Cancelled</th>
        </tr>
        {% for registration in cancelled %}
            <tr>
                <td><a href="{{ registration.get_absolute_url }}">{{ registration.registration_number }}</a></td>
                <td>{{ registration.service_number }}</td>
                <td>{{ registration.start_point }}</td>
                <td>{{ registration.finish_point }}</td>
                <td>{{ registration.via }}</td>
                <td>{{ registration.date|date:"j M y" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

{% endblock %}

busstops/templates/busstops/stoppoint_detail.html
{% extends 'page.html' %}

{% block content %}

<div itemscope itemtype="https://schema.org/BusStop">

<h1 itemprop="name">{{ stoppoint.get_qualified_name }}</h1>

{% if text %}
<p>{{ text }}</p>
{% endif %}

{% if stoppoint.bearing %}
<p>Buses travel {{ stoppoint.get_bearing_display }} from here</p>
{% endif %}

{% if stoppoint.latlong %}
    <span itemprop="geo" itemscope itemtype="https://schema.org/GeoCoordinates">
        <meta itemprop="latitude" content="{{ stoppoint.latlong.y }}" />
        <meta itemprop="longitude" content="{{ stoppoint.latlong.x }}" />
    </span>

    <div class="stop-map" id="map" data-indicator="{{ stoppoint.indicator }}"{% if stoppoint.get_heading is not None %} data-heading="{{ stoppoint.get_heading }}"{% endif %}></div>
{% endif %}

<div class="asides">

{% include 'departures.html' with departures=departures %}

{% if services %}
    <div class="aside box">
    <h2>{% include 'modes.html' with modes=modes noun='services' %}</h2>
    <ul>
    {% for s in services %}
        <li><a href="{{ s.get_absolute_url }}">{{ s }}</a></li>
    {% endfor %}
    </ul>
    </div>
{% endif %}

{% if nearby %}
<div class="aside box">
    <h2>Nearby stops</h2>
    {% include 'stops.html' with stops=nearby %}
</div>
{% endif %}

</div>

</div>

{% endblock %}

busstops/templates/busstops/variation_list.html
{% extends 'page.html' %}

{% block title %}{{ object_list.0.registration.registration_number }} – Bus Times{% endblock %}

{% block content %}

<h1>{{ object_list.0.registration.registration_number }}</h1>

<table>
    <tr>
        <th scope="row"></th>
        <td>{{ object_list.0.registration.service_number }}</td>
    </tr>
    <tr>
        <th scope="row">From</th>
        <td>{{ object_list.0.registration.start_point }}</td>
    </tr>
    <tr>
        <th scope="row">To</th>
        <td>{{ object_list.0.registration.finish_point }}</td>
    </tr>
    <tr>
        <th scope="row">Via</th>
        <td>{{ object_list.0.registration.via }}</td>
    </tr>
</table>

<h2>History</h2>

<table>
    <th scope="col">#</th>
    <th scope="col">Received</th>
    <th scope="col">Effective date</th>
    <th scope="col">Status</th>
    <th scope="col">Details</th>
    <th scope="col">Publication text</th>
    {% for variation in object_list %}
        <tr>
            <td>{{ variation.variation_number }}</td>
            <td>{% firstof variation.date_received|date:"j M y" '' %}</td>
            <td>{% firstof variation.effective_date|date:"j M y" '' %}</td>
            <td>{{ variation.registration_status }}</td>
            <td>{{ variation.service_type_other_details }}</td>
            <td>{{ variation.publication_text|linebreaksbr }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}

busstops/templates/busstops/vehicle_detail.html
{% extends 'page.html' %}

{% block content %}

<h1>{{ object }}</h1>

{% if object.vehicle_type %}
    <p>{{ object.vehicle_type }}</p>
{% endif %}

<form>
<input type="date" name="date" value={{ date.isoformat }}>
<input type="submit">
</form>

{% if locations %}
<div id="cartograph" style="height:100vh"></div>

<link rel="stylesheet" href="/static/js/bower_components/leaflet/dist/leaflet.css" />
<script src="/static/js/bower_components/leaflet/dist/leaflet.js"></script>
<script>
(function() {
    function getRandomColor() {
        var letters = '0123456789';
        var color = '#';
        for (var i = 0; i < 3; i++) {
            color += letters[Math.floor(Math.random() * 10)];
        }
        return color;
    }

    function getMarker(latlng, direction) {
        var html = '';
        if (direction !== null) {
            html = '<div class="arrow" style="-ms-transform: rotate(' + direction + 'deg);-webkit-transform: rotate(' + direction + 'deg);-moz-transform: rotate(' + direction + 'deg);-o-transform: rotate(' + direction + 'deg);transform: rotate(' + direction + 'deg)"></div>';
        }
        return L.marker(latlng, {
            icon: L.divIcon({
                iconSize: [16, 8],
                html: html,
                className: 'just-arrow'
            })
        });
    }

    var map = L.map('cartograph'),
        tileURL = 'https://bustimes.org/styles/klokantech-basic/{z}/{x}/{y}' + (L.Browser.retina ? '@2x' : '') + '.png',
        latlng,
        service,
	bounds = L.latLngBounds();

    L.tileLayer(tileURL).addTo(map);

    {% for location in locations %}
        {% if object.region %}
            {% ifchanged location.vehicle %}
                service = '<a href="{{ location.vehicle.get_absolute_url }}">{{ location.vehicle }}</a><br>';
            {% endifchanged %}
        {% else %}
            {% ifchanged location.service %}
                service = '{% if location.service %}<a href="{{ location.service.get_absolute_url }}">{{ location.service.line_name }}</a><br>{% endif %}';
            {% endifchanged %}
        {% endif %}
        latlng = [{{ location.latlong.y }},{{ location.latlong.x }}];
        bounds.extend(latlng);
        getMarker(latlng, {% if location.heading is not None %}{{ location.heading }}{% else %}null{% endif %}).bindPopup(service + "{{ location.datetime }}").addTo(map);
    {% endfor %}
    map.fitBounds(bounds);
    map.setMaxBounds(bounds.pad(.5));
})();
</script>
{% else %}
    <p>Sorry, nothing found for {{ date }}</p>
{% endif %}

    {% for location in locations %}
        {% if object.region %}
            {% ifchanged location.vehicle %}
                <p>{{ location.datetime }} - <a href="{{ location.vehicle.get_absolute_url }}">{{ location.vehicle }}</a></p>
            {% endifchanged %}
        {% else %}
            {% ifchanged location.service %}
                <p>{{ location.datetime }}{% if location.service %} - <a href="{{ location.service.get_absolute_url }}">{{ location.service.line_name }}</a>{% endif %}</p>
            {% endifchanged %}
        {% endif %}
{% endfor %}

{% endblock %}